volumes:
    portfolio-postgres:
        name: 'portfolio-postgres'
        driver: local

    portfolio-redis:
        name: 'portfolio-redis'
        driver: local

networks:
    nw:
        driver: bridge

services:
    db:
        image: portfolio-postgresql
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - portfolio-postgres:/var/lib/postgresql/data
        networks:
            - nw

    redis:
        image: portfolio-redis
        ports:
            - 6379:6379
        volumes:
            - portfolio-redis:/data
        networks:
            - nw

    mailer:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - nw

    assets:
        image: portfolio-assets
        ports:
            - 5173:5173
        user: node
        volumes:
            - .:/srv/www/app
        networks:
            - nw

    app:
        image: portfolio-laravel
        depends_on:
            - db
            - redis
            - mailer
        ports:
            - 5000:5000
        volumes:
            - .:/srv/www/app
        networks:
            - nw
