#!/usr/bin/env bash

echo "Building 'ubuntu' base images"
docker image build --build-arg uid=$(id -u) --build-arg gid=$(id -g) --pull --force-rm --no-cache -t 'portfolio-ubuntu' ubuntu/

echo "Building 'php' base images"
docker image build --force-rm --no-cache -t 'portfolio-php' php/

echo "Building 'node' base images"
docker image build --build-arg uid=$(id -u) --build-arg gid=$(id -g) --pull --force-rm --no-cache -t 'portfolio-node' node/

echo "Building 'postgresql' base images"
docker image build --pull --force-rm --no-cache -t 'portfolio-postgresql' postgresql/

echo "Building 'laravel' images"
docker image build --force-rm --no-cache -t 'portfolio-laravel' laravel/

echo "Building 'assets' images"
docker image build --force-rm --no-cache -t 'portfolio-assets' laravel/assets/

echo "Building 'redis' images"
docker image build --force-rm --no-cache -t 'portfolio-redis' redis/
