#!/usr/bin/env bash

echo "Building 'ubuntu' base images"
docker image build --pull --force-rm --no-cache -t 'ubuntu:22.04' ubuntu/

echo "Building 'php' base images"
docker image build --force-rm --no-cache -t 'php:8.2' php/

echo "Building 'node' base images"
docker image build --pull --force-rm --no-cache -t 'node:20' node/

echo "Building 'postgresql' base images"
docker image build --pull --force-rm --no-cache -t 'postgresql:14' postgresql/

echo "Building 'laravel' images"
docker image build --force-rm --no-cache -t 'laravel:10' laravel/

echo "Building 'assets' images"
docker image build --force-rm --no-cache -t 'laravel-assets:1.3' laravel/assets/
